apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduledscaling-frontend
  namespace: default
  labels:
    app: scheduledscaling-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduledscaling-frontend
  template:
    metadata:
      labels:
        app: scheduledscaling-frontend
    spec:
      containers:
      - name: frontend
        image: scheduledscaling-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://scheduledscaling-api:80"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: scheduledscaling-frontend
  namespace: default
spec:
  selector:
    app: scheduledscaling-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
